spring.application.name=barberapp

spring.datasource.url=jdbc:postgresql://localhost:5432/db_barberapp
spring.datasource.username=postgres
spring.datasource.password=2008

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081